### PR TITLE
Remove init script

### PR DESCRIPTION
**Pull request by bturner-r7**
This removes the embedded init script and uses the init script installed by Nexpose.

We originally overwrote the init script to get a proper status indicator, but this behavior is being moved to upstream Nexpose.  This fix should also allow managing systemd services.

### CODE REVIEW

**Comment by rhass** [comment]
:+1:

**Comment by bcall-r7** [comment]
@rhass 
https://cdn.meme.am/instances/43187420.jpg

**Comment by bturner-r7** [comment]
Hello old friend!

**Comment by rhass** [comment]
Hello! Just so you know -- you all should have publish rights in the supermarket, I can also transfer ownership to who ever you would like.

**Pull request merged**
